### ISSUE TITLE
KIT-0001: Codable Routing

### ISSUE THREAD

**Issue by seabaylea** [IBM-Swift/evolution#2]

**Comment by JacopoMangiavacchi** [comment]
I like a lot the proposed solution and I’d love the async/await/promises alternative solution in the future.

Anyway as this a simplified high level api that do not replace the current lower level api I wonder if it couldn’t be possible to also add support for the Codable protocol in the BodyParser.

I mean today you can already use Codable in Kitura in this way with no BodyParser:

```
struct Name: Codable {
   let name: String
}

router.post("/") { request, response, next in
    do {
        var data = Data()
        if try request.read(into: &data) > 0 {
            let name: Name = try JSONDecoder().decode(Name.self, from: data)
            try response.status(.OK).send(data: JSONEncoder().encode(name)).end()
        }
    }
    catch {
    }
}
```


With a Codable support in BodyParser we can have this:

```
struct Name: Codable {
   let name: String
}

router.all(“/*”, middleware: BodyParser())
router.post("/") { request, response, next in
    if let name: Name = request.body(Name.self) {
        try response.status(.OK).send(data: JSONEncoder().encode(name)).end()
    }
}
```

**Comment by seabaylea** [comment]
Hey @JacopoMangiavacchi. Does this cover the sort of thing your looking for?
https://github.com/IBM-Swift/Kitura/pull/1163

**Comment by JacopoMangiavacchi** [comment]
Thank you @seabaylea, that exactly cover my scenario

**Comment by seabaylea** [comment]
Closing as this was delivered in Kitura 2.0.0. A proposal for adding support for URL encoded query parameters should be arriving later today.
